### ISSUE TITLE
Перевести инструкцию на русский

### ISSUE THREAD

**Issue by dapi** [KonishchevDmitry/investments#1]
Так как нужна эта утилита только для резидентов РФ ;)

**Comment by KonishchevDmitry** [comment]
Я бы сказал, что для начала было бы неплохо в принципе иметь инструкцию по установке. :) Сейчас нет информации ни о том, как собрать, ни о том, как сформировать минимальный конфиг, чтобы ей можно было пользоваться.

Русский, как по мне - меньшая из проблем. Если человек инвестирует через американского брокера, то бояться английского довольно странно. Я лично на всех устройствах использую исключительно американскую локаль - интерфейсы на английском для мня всегда были понятнее и лаконичнее, а т. к. проект в первую очередь для себя и just for fun, то локализацию в ближайшем будущем точно не планировал делать.

А вот если на утилиту будет спрос, то инструкцию по сборке и настройке написать безусловно надо.

**Comment by dapi** [comment]
Ясно. Я подумываю сделать веб-морду (там проще представить публике).

Вот изучаю варианты: толи использовать внутри ваш скрипт, толи писать свою реализацию.

**Comment by Worm** [comment]
Установка под MacOS X:
1) Установка RUST. "curl https://sh.rustup.rs -sSf | sh"
2) git clone https://github.com/KonishchevDmitry/investments.git
3) cargo install
4) Теперь в терминале доступна комманда investments

Писал по памяти, может кому то поможет)

**Comment by KonishchevDmitry** [comment]
Добавил в README минимальную документацию, в которой описал основные моменты по установке и использованию.

Данный issue закрываю как won't fix, т. к. интернационализация данного проекта не рассматривается в хоть каком-то обозримом будущем.
