### ISSUE TITLE
Проблема с обработкой кода ISIN

### ISSUE THREAD

**Issue by IlyaKarpelyuk** [KonishchevDmitry/investments#12]
Добрый день, Дмитрий!

Продолжаю тестировать Вашу программу на живом счете и обнаружил еще одну ошибку.

![image](https://user-images.githubusercontent.com/65602043/83865893-94cd3780-a72f-11ea-9262-ad45b6a71f62.png)

Программа ругается на выплату дивидендов одним тикером - ETN (Eaton Corporation), компания самая обычная, сделка - лонг. Я так думаю программа не воспринимает вот эти символы в отчете Interactive Brokers - ETN(**IE**00B8KQN827). То есть код ISIN отличный от начинающегося с **US**. 

Сама компания из Ирландии, но торгуется на NYSE, причем напрямую - не ADR (если не ошибаюсь) и дивиденты выплачивает так же в USD.

Можете пофиксить этот баг, что бы программа могла считывать ISIN-коды **IE** и другие, по возможности.

Заранее большое спасибо!

Свои отчеты из Interactive Brokers прилагаю.
[ActivityRUB.zip](https://github.com/KonishchevDmitry/investments/files/4735577/ActivityRUB.zip)

**Comment by KonishchevDmitry** [comment]
Добрый день!

Спасибо за отчет и подробности! Обязательно добавлю его в регрессионные тесты. :)
ISIN я не паршу, но причина проблемы понятна - сегодня/в выходные поправлю.

FYI:

Сейчас программа еще ругается, если попросить у нее сформировать налоговую декларацию по вашему отчету:

`E: Failed to process income from stock trading: Failed to calculate results of CSGS selling order from 04.06.2020: An attempt to make currency conversion for future date: 08.06.2020.`

Я пока не считаю это за ошибку - это все из-за T+2 из Trade Confirmation Report. Сделка завершится только 08.06.2020, курса доллара на эту дату нет, а в налоговой декларации все должно быть четко - никаких допущений. :)

Можно, конечно, наверное как-то игнорировать и ругаться не фатально, но пока ничего такого не сделал, т. к. для меня это не было актуально - просто не скачивал Trade Confirmation Report раньше времени.
