### ISSUE TITLE
Non-continuous periods error during parsing IB statements

### ISSUE THREAD

**Issue by KonishchevDmitry** [KonishchevDmitry/investments#14]
> ...
> программа, как я понял не умеет видеть выходные дни между csv-отчетами. У меня есть csv-отчет по старому аккаунту заканчивающийся 19.06.2020 (это пятница), в IB я могу сформировать новый csv-отчет (по новому аккаунту, но это не важно) только с 22.06.2022 (понедельник) или с 19.06.2020 (пятница), то есть по рабочим дням. И если я их "скармливаю" Вашей программе, то она выдает ошибку (см. скриншот)
>
> Получается, что приходится править csv-отчет в любом случае, редактируя начальную дату на следующий день 20.06.2020 (суббота), даже если он нерабочий. 
>
> Другими словами, программа не может мержить отчеты одни из которых заканчиваются в пятницу, а другие начинаются в понедельник.

![error](https://user-images.githubusercontent.com/65602043/86335397-1fce1e80-bc57-11ea-815a-7b1eced2d985.jpg)

_Originally posted by @IlyaKarpelyuk in https://github.com/KonishchevDmitry/investments/issues/13#issuecomment-652868907_

**Comment by KonishchevDmitry** [comment]
Да, действительно - что-то они недавно поменяли у себя. Я всегда скачивал Year to Date отчеты, и там всегда было 1 января, а вот сейчас стали генериться со 2-ого.

Видимо придется разрешать небольшие дыры в отчетах. :( Не подгружать же ради этого календарь работы бирж. :)

Починю на выходных или на следующей неделе.

**Comment by Bsplesk** [comment]
Календарь вещь хорошая.

**Comment by KonishchevDmitry** [comment]
Хорошая - не спорю, но это лишняя зависимость. Я вот сейчас для котировок поддерживаю 4 сервиса - и это не от хорошей жизни: то вдруг API поменяют, и все перестает работать, то вдруг делают API платным, то вводят абсолютно драконовские rate limits вроде максимум 5 запросов в минуту.

Так что ради дырок в отчетах привязываться к календарю не хотелось бы - у меня не так много свободного времени, чтобы потом все это дело поддерживать. :)
