### ISSUE TITLE
Проблема с подсчетом дробных акций

### ISSUE THREAD

**Issue by IlyaKarpelyuk** [KonishchevDmitry/investments#15]
Добрый день, Дмитрий!

Как всегда, продолжаю тестировать Вашу программу. :)

Купил вчера дробные акции и столкнулся с проблемой, что программа не понимает покупку дробных акций (fractional shares), отраженных в отчете. Сама продажа дробных акций не осуществлялась, так же дивиденды по ним не приходили. Более того, в этот же день (вчера) я докупил дробные доли до целых чисел и с того дня у меня в портфеле все акции целые.

Сам отчет направляю по почте, так же прикладываю отчет со старого счета, для совместимости (как Вы помните, я перевел акции с одного счета на другой; старый отчет заканчивается 19.06.2020, а новый начинается с 22.06.2020 (следующим рабочим днем)).

Буду крайне признателен, если получиться добавить возможность учета дробных акций (fractional shares).
Заранее спасибо!

P.S. Дивиденды рассчитываются очень просто, вот официальный ответ и формула IB (аналогичный метод вероятно можно экстраполировать и на расчет налога):
https://www.interactivebrokers.com/lib/cstools/faq/#/content/faq%3A%2F%2FpageId%3D84609891?articleId=83261303

P.P.S. Еще, я так понял, дробные акции не могут быть больше чем десятитысячные доли (то есть не более 4-х знаков после запятой, например 3.5649)

![image](https://user-images.githubusercontent.com/65602043/87027259-946c0480-c1e5-11ea-9923-1c0ad4dd0cd0.png)

**Comment by KonishchevDmitry** [comment]
Добрый день, Илья!

Да - дробные акции я пока что считал какой-то экзотикой и не пытался поддерживать. Да и появились они в IB относительно недавно.

Там скорее будет не с дивидендами проблема, а в FIFO придется заниматься округлениями, из-за чего потом цифры будут немного расходиться.

Спасибо за отчеты! Не могу сейчас пообещать какие-то сроки, но постараюсь в обозримом будущем сделать поддержку.

**Comment by KonishchevDmitry** [comment]
@IlyaKarpelyuk, а у вас есть понимание, как в случае с fractional shares будут рассчитываться комиссии? Как-то они по этому поводу никакой конкретики не дают. Сейчас начал делать поддержку, и пока не понимаю, в какую сторону менять логику текущего калькулятора комиссий.

**Comment by IlyaKarpelyuk** [comment]
Я запрошу сегодня поддержку IB, может они что-нибудь скажут, как рассчитывается комиссия.
Плюс, я последние дни менял тарифы с Fixed на Tired и обратно, пытаясь определить где выгоднее. И как мне кажется, на момент, когда я покупал fractional shares (08.07.2020) был тариф Tired. Ниже скриншот для наглядности комиссий, впрочем тоже самое но менее наглядное в файле Activity.
![image](https://user-images.githubusercontent.com/65602043/87392760-bedb0a80-c5b5-11ea-94f8-da0cd2330af7.png)

**Comment by KonishchevDmitry** [comment]
Да, там у вас явно был Tiered - поэтому и спросил - вдруг вы знаете, т. к. с Tiered по размеру комиссии понять что-то практически невозможно - уж больно он непредсказуемый. Ок, спасибо!

**Comment by IlyaKarpelyuk** [comment]
Спросил в чате службы поддержки IB, ответить не смогли, попросили создать тикер, создал его, жду ответа, надеюсь помогут. Как дадут ответ, отпишусь.

**Comment by KonishchevDmitry** [comment]
Добавил поддержку в том объеме, в котором я могу нафантазировать себе по предоставленным вами отчетам. В итоге у вас везде получилось целое количество бумаг, и промежуточных отчетов, где отражались бы дробные результаты, у меня нет, но, думаю, там сюрпризов не будет.

**Comment by IlyaKarpelyuk** [comment]
Добрый день, Дмитрий!

Вот что мне ответила служба поддержки IB:
_Спасибо, что обратились в Службу поддержки Interactive Brokers.

Максимальная комиссия в 1% от суммы сделки не может превышать минимальную комиссию в 0,35 USD, поэтому при сумме сделки в 18 USD комиссия не может превышать 0,18 USD._

То есть, если разобрать на примере. Например 2-ую строчку отчета (см. скриншот выше)
Я купил 0.2295 шт. акций CHRW за 80.47, соответственно комиссия, со слов поддержки, составляет: 0.2295*80.47*0.01=0.18 USD

Осталось уточнить откуда тогда комиссия в 0.38 и 0.36 (см. скриншт).
Буду продолжать пытать поддержку. :)

**Comment by IlyaKarpelyuk** [comment]
Добрый день, Дмитрий!
Вот что мне написала поддержка в итоговом ответе:

_Нами предоставлена информация о минимальной и максимальной комиссии от нас, как от брокера (для маленьких объемов она составляет 0,35 на ордер), далее к ней добавляются биржевые сборы - Расценки -- Комиссии -- Tiered -- США Биржевые сборы._

_В случаях, когда биржа предоставляет рибейт, мы возвращаем часть или все сбережения непосредственно вам. 1_

_Если IBKR получит рибейт за исполнение сделки с акциями, на которые распространяется Регулирование системы нац. рынка (Regulation NMS), у маркет-мейкера, в скрытом пуле или через поставщика ликвидности на IB ATS, IBKR зачислит всю сумму клиенту, пользующемуся структурой комиссий Tiered, в кач-ве возврата от площадки._

**Comment by KonishchevDmitry** [comment]
Да - Tiered очень сложно рассчитывается - поэтому я пока в `analyse` и `simulate-sell` считаю по Fixed. Спасибо! Буду иметь в виду.
