### ISSUE TITLE
Анализ дивидендов иностранных эмитентов в отчетах Открытия

### ISSUE THREAD

**Issue by nikitabuida** [KonishchevDmitry/investments#19]
Дмитрий, добрый день!
Видел в описании, что вы не делали анализ иностранных дивов у наших брокеров, так как у вас нет примеров файлов брокерских отчетов.
А если вам предоставить образцы файлов, то вы бы стали такой функционал добавлять?

**Comment by KonishchevDmitry** [comment]
Добрый день.

Если там формат записи такой, что из него можно вычленить размер полученного дивиденда и уплаченный налог, то по идее это не должно быть сложно. По срокам обещать не могу, но как появится свободное время - готов поддержать.

Можете прислать мне отчеты на konishchev@gmail.com. Желательно за все время существования счета. Это позволит сделать более полноценную поддержку, т. к., к примеру, в IB в феврале бывают пересчеты уплаченных налогов (но это скорее справедливо только для ETF) + я смогу проверить, что результирующий баланс на счете по моим подсчетам сходится с точностью до копейки с тем, что указано в отчете - а это хороший признак того, что все посчитано правильно.

**Comment by KonishchevDmitry** [comment]
Переименовал тикет, т. к. вынес запрос относительно Тинькова в отдельный тикет - #26.

**Comment by nikitabuida** [comment]
Дмитрий, выслал вам полный брокерский отчет по Открытию на почту. Спасибо!

**Comment by KonishchevDmitry** [comment]
Спасибо. Эх, надеялся на лучшее. :) Имена эмитентов в описании операции такие, что их невозможно отмапить на stock symbol ни по открытым позициям, ни по какой-либо еще информации из отчета. Видимо, тут единственный выход - вводить ручной маппинг на уровне конфига.

**Comment by nikitabuida** [comment]
Для налогового отчета наверное это не важно. А вот для всего остального да, Открывашка во всех отчетах и в Квике использует эти странные имена.

**Comment by KonishchevDmitry** [comment]
Ну, формально - да, не важно. Но т. к. у моей программы генерация 3-НДФЛ - это всего лишь одна из функций, то у меня каждая операция по бумаге обязательно провязывается со stock symbol (чтобы общую доходность, к примеру, посчитать), и не провязать я не могу - иначе весь остальной функционал поедет.

**Comment by nikitabuida** [comment]
> 
> 
> Ну, формально - да, не важно. Но т. к. у моей программы генерация 3-НДФЛ - это всего лишь одна из функций, то у меня каждая операция по бумаге обязательно провязывается со stock symbol (чтобы общую доходность, к примеру, посчитать), и не провязать я не могу - иначе весь остальной функционал поедет.

Если я как-то могу помочь, то готов.

**Comment by KonishchevDmitry** [comment]
@nikitabuida, вроде поддержал Московскую Биржу в 3.4.0. На SPB-отчет пока не смотрел, т. к. у него совсем другой формат. Но гляну.

**Comment by nikitabuida** [comment]
> 
> 
> @nikitabuida, вроде поддержал Московскую Биржу в 3.4.0. На SPB-отчет пока не смотрел, т. к. у него совсем другой формат. Посмотрю чуть позже.

Огромное спасибо!

**Comment by KonishchevDmitry** [comment]
Добавил поддержку SPB-биржи (в рамках предоставленного отчета).
