### ISSUE TITLE
Требуется пример конфига config.yaml

### ISSUE THREAD

**Issue by Worm** [KonishchevDmitry/investments#2]
Добрый день! Хочу воспользоваться Вашим скриптом, всё установил, пробую использовать, однако не хватает примера конфига config.yaml, который требуется для использования скрипта. Прошу сбросить хоть какой то пример. Заранее огромное спасибо

**Comment by KonishchevDmitry** [comment]
Добрый день! Постараюсь в течение недели найти время и сделать хотя бы минимальную документацию по установке и использованию.

**Comment by Worm** [comment]
Спасибо. Будем ждать. Без примера конфига, тяжко)

**Comment by KonishchevDmitry** [comment]
Кажется, основные моменты описал.
