### ISSUE TITLE
Ошибка spinoff

### ISSUE THREAD

**Issue by IlyaKarpelyuk** [KonishchevDmitry/investments#20]
Добрый день, Дмитрий!

В первую очередь, спасибо за Вашу, столь полезную программу для расчета налогов!

Я столкнулся со следующей проблемой, компания Pfizer (PFE) выделела из себя свое подразделение в отдельную компанию - Viatris (VTRS) и все держатели акций Pfizer (PFE) получили акции этой компании. Этот процесс называется спин-офф или spin-off https://ru.wikipedia.org/wiki/Выделение_организации

Со мной так и произошло, но к сожалению программа не хочет счтать налог из-за этих новых акций.
Можете ли исправить этот недочет? Отчеты отправил по почте.

Огромная благодарность!

![image](https://user-images.githubusercontent.com/65602043/103464692-b2ef2a80-4d46-11eb-9527-fcaf924d963f.png)

**Comment by KonishchevDmitry** [comment]
Добрый день, Илья.

А у вас есть понимание, как оно вообще в принципе работает и должно декларироваться?

Я сейчас поглядел с калькулятором на ваши отчеты - пока вижу следующее:
1. Есть Corporate Action от 2020-11-17 (он же на скриншоте). Из него, насколько я понимаю, следует, что 9.3059 акций были "подарены" вам.
2. Также я вижу несколько операций покупки VTRS от 2020-11-17, которые добивают общее их количество до целого числа. Это ваши операции, или это часть корпоративного действия?

Со вторым пунктом в целом особых вопросов нет, а вот с первым не очень понятно, как его трактовать с точки зрения налогов. Я вижу два варианта:
1. Считать, что вы их "купили" за $0.
2. Откуда-то взять их рыночную цену и считать, что они были "куплены" по этой цене.

Учитывая то, что spin-off - это выделение части компании, в результате которого акции материнской компании падают, сходу мне (как человеку, платящему налоги :) ) кажется логичным второй вариант. Хотя первый выглядит гораздо "ближе" к отчетам.

В пользу первого варианта также можно предположить, что это стоит рассматривать как разновидность Return of capital, который выплачивается в виде дивидендов: как будто вы его получили, но тут же сконвертировали в акции, а при продаже будете вынуждены заплатить налог со всей суммы - т. е. просто отсрочили уплату налога. Если смотреть с этой позиции, то оно наверное даже выглядит логичнее второго варианта.

Yahoo Finance показывает это корпоративное действие как `1054:1000 Stock Split`, что с погрешностью в пару акций похоже на ваше корпоративное действие (для расчета брал PFE volume и VTRS close price из отчета).

**Comment by IlyaKarpelyuk** [comment]
Здравствуте, Дмитрий.

Почитал я об особенностях американского налогооблажения spinoff, которое, в принципе, можно применить на Российские реалии, но об этом чуть позже.

Во-первых, прокомментирую по пунктам.
По отчетам:
1. Да, Вы совершенно правы, 9.3059 акций действительно были "подарены" мне, в рамках корпоративного действия по выделению новой компании. По формуле из отчета _(Spinoff  124079 for 1000000)_ 124079/1000000*75=9.3059 (где 75 - количество имеющихся акций PFE)
2. Все дальнейшие операций по покупке VTRS были совершенны мною и уже никак не относятся к действиям компании PFE.

По поводу как обсчитывать налог по "дарению" акций в рамках spinoff, наткнулся на интересные статьи, которые привожу ниже, вот ссылки:
- http://www.spinoffprofiles.com/spinoff-tax-basis-and-tax-treatment
- https://www.costbasis.com/stkchanges/spinoffs.html
_"Typically, in the United States, shareholders in distribution-type spinoffs **are taxed on gains or losses in the tax year in which they sell the shares.**"_
Так, что похоже, это именно первый вариант, то есть, взымание налога в момент продажи. Но вот, от какой стоимости и как именно расчитать налоги в момент продажи и откуда автоматически подтягивать данные по cost basis, на момент "дерения", я пока не знаю. Если, реализация этого слишком сложная задача, может действительно имеет смысл указать эти 9.3059 за 0$?!

**Comment by KonishchevDmitry** [comment]
Да, выглядит довольно запутанно. А если еще учитывать то, что покупаться акции могли в разное время, то к каждому такому корпоративному действию придется прикладывать табличку по расчету. :)

Давайте я пока реализую это как покупку по нулевой цене. На самом деле, это ведь даже не такой уж и плохой вариант, как может показаться с первого взгляда: если впоследствии продавать акции обеих компаний, то никаких дополнительных расходов на налоги не будет - падение в стоимости родительской компании просальдируется с доходом от продажи дочерней по полной стоимости, и в итоге выйдет все вполне честно - как для вас, так и для налоговой.

**Comment by IlyaKarpelyuk** [comment]
Да, Дмитрий, я то же пришел к такой мысли, оптимальное решение.
Спасибо за реализацию!

**Comment by KonishchevDmitry** [comment]
Поддержал в 2.6.3.
