### ISSUE TITLE
tax-statement tinkoff wrong report format

### ISSUE THREAD

**Issue by MaximKiselev** [KonishchevDmitry/investments#21]
` ←[31mE: Error while reading "broker-report-2020-07-01-2020-12-31.xlsx" broker statement: The row contains non-empty cells between column cells: [String("10 из "), Empty].←[0m`

привет. спасибо за полезную тулзу.  в общем не пашет с тиньковым. засунул брокерский отчет - выдает ошибку. походу опять они формат поменяли.

**Comment by KonishchevDmitry** [comment]
Привет. У меня на моих отчетах не воспроизводится. Пришлите, пожалуйста, свои отчеты на konishchev@gmail.com - я посмотрю на ваш конкретный случай.

**Comment by MaximKiselev** [comment]
отослал. спасибо...

**Comment by KonishchevDmitry** [comment]
Спасибо за отчет! Правда, к сожалению, вынужден вас расстроить. :( Та ошибка, о которую вы споткнулись - это мелочь, ее поправить легко, но вот в остальном - у вас довольно сложный отчет:

Как написано в https://github.com/KonishchevDmitry/investments#бкс-открытие-брокер-and-тинькофф + #19, я пока не умею парсить дивиденды, налоги и пр. у российских брокеров - только у IB + Firstrade.

Я сейчас попробовал пока через ручную правку кода и самого отчета заставить его распарситься хотя бы как-то, чтобы оценить масштаб необходимых доработок, и увидел несколько мест, показывающих недружелюбность Тинькоффских отчетов к парсингу + к примеру, по одной из акций у вас был сплит, но в отчете нет никаких упоминаний о корпоративных действиях.

Это все выглядит как решаемые проблемы, но на их решение потребуется время, поэтому в ближайшем будущем я, к сожалению, их поддержку обещать вам не могу.

**Comment by MaximKiselev** [comment]
ok. спасибо. с рождеством 🎄 . попробую сам поковырять тогда.

**Comment by KonishchevDmitry** [comment]
Поправил в 2.7.0 все проблемы с парсингом, которые мне встретились. Теперь отчет читается без проблем. Но нужно добавить вот такие строчки в конфиг, т. к. в отчетах Тинькофф напрочь отсутствует какая-либо информация о корпоративных действиях:
```yaml
corporate_actions:
  - type: stock-split
    date: 27.10.2020
    symbol: NEE
    ratio: 4:1
```

Правда, основная задача, ради которой все затевалось (декларация доходов с дивидендов) пока что так полноценно и не решена. Вынес эту проблему в отдельный тикет с призывом к пользователям, т. к. здесь она затеряется - #26.
