### ISSUE TITLE
Unable to find USD/RUB currency rate for 11.01.2021 with 3 days precision.

### ISSUE THREAD

**Issue by Worm** [KonishchevDmitry/investments#23]
Привет!

После крайнего обновления при попытке сделать анализ портфеля выдает ошибку парсинга курса валют на текущую дату

`investments analyse ib
E: Failed to calculate results of VWO selling order from 11.01.2021: Unable to find USD/RUB currency rate for 11.01.2021 with 3 days precision.`

**Comment by KonishchevDmitry** [comment]
Спасибо, поправил в 2.6.5.
