### ISSUE TITLE
Tax-statement: display fees (inactivity/snapshots/etc)

### ISSUE THREAD

**Issue by esemi** [KonishchevDmitry/investments#24]
Доходы от сделок с ЦБ можно уменьшить на прочие комиссии на аккаунте. В случае с IB это наверное чаще всего комиссия за неактивность аккаунта при балансе меньше $100k.
Было бы логично вывести сумму комиссий за отчётный год отдельной табличкой

**Comment by KonishchevDmitry** [comment]
Вывести-то не сложно - я пока не знаю, как это лучше задекларировать.

Для российских брокеров я эти комиссии вывожу и сальдирую с продажами, т. к. там команда `tax-statement` используется разве что для сверки, и декларация не заполняется.

А вот для зарубежных брокеров я декларацию заполняю, и не очень понятно, куда их там вписывать. У меня была мысль добавлять фиктивный доход с именем "Комиссия брокера: ...", нулевым доходом и размером вычета, равным размеру комиссии - оно даже работает как надо, но вот не уверен что это не смутит налоговую. Поэтому пока ничего такого не делал, благо лично для меня это не особо актуально.

Есть идеи, как это правильнее сделать так, чтобы у налогового инспектора не возникло желания запросить уточнения?

**Comment by esemi** [comment]
Вроде по стандартной практике комиссии просто учесть в расходах какой либо сделки. А если смутит - то объяснить в пояснительной части, можно и заранее

**Comment by KonishchevDmitry** [comment]
Пожалуй соглашусь. Раньше я такой вариант не рассматривал, т. к. пока что старался, чтобы отчеты брокера, таблички, которые я генерю, и итоговая декларация ложились друг на друга максимально прозрачно. Но наверное это действительно самый компромиссный вариант. К примеру, всегда записывать их в первую сделку.
