### ISSUE TITLE
E: Unable to calculate trade commission: Commission currency doesn't match trade currency: RUB vs USD.

### ISSUE THREAD

**Issue by latonita** [KonishchevDmitry/investments#25]
Добрый день, @KonishchevDmitry 
попробовал сегодня запустить с дефолтным конфигом (добавлены токены, добавлены файлы отчетов из тинькофф)

investments analyse tinkoff
E: Unable to calculate trade commission: Commission currency doesn't match trade currency: RUB vs USD.

На счете только иностранные акции.

**Comment by KonishchevDmitry** [comment]
Такое я пока не поддерживаю - да, но, чувствую, все-таки придется...

А как оно у вас выглядит? Вы покупаете условный AAPL на СПБ'шной бирже за USD, комиссии во всех тарифах выражены в процентах, а Тинькофф берет и начисляет ее в рублях?

**Comment by latonita** [comment]
да, я покупаю условный AAPL за USD, но комисии везде и начисляются и указаны в USD.

**Comment by KonishchevDmitry** [comment]
Спасибо, понял в чем проблема. На будущее, чтобы не забыть - надо учить текущий калькулятор комиссий работать с разными валютами вне зависимости от базовой.

Я бы сейчас наверное мог бы быстро закрыть эту проблему, дав возможность задавать фейковый калькулятор комиссий, который всегда возвращал бы нули, пока я не исправлю текущий, но, учитывая то, что у вас все сделки на СПБ бирже, вы тут же придете ко мне с новыми проблемами вроде https://github.com/KonishchevDmitry/investments/issues/21#issuecomment-755429947, т. к. текущая поддержка Тинькофф довольно ограниченная и по факту подходит разве что для торговли ETF'ами на Московской Бирже. Поэтому, видимо, мне тут надо сразу смотреть в сторону того, чтобы инвестировать свое время в полноценную поддержку Тинькова.

**Comment by KonishchevDmitry** [comment]
Данную конкретную проблему я поправил в v2.6.11. Улучшать поддержку Тинькофф (дивиденды, особенности самого брокера) тогда уже буду в #21.
