### ISSUE TITLE
Тинькофф: Декларирование дохода с дивидендов иностранных эмитентов

### ISSUE THREAD

**Issue by KonishchevDmitry** [KonishchevDmitry/investments#26]
**Обращение к пользователям**

В данный момент брокерские отчеты Тинькофф содержат недостаточное количество информации по дивидендам зарубежных эмитентов, чтобы по ним можно было автоматически заполнять налоговую декларацию.

Ниже - запрос, который я отправил в поддержку Тинькова, и их ответ. Если вы заинтересованы в том, чтобы с помощью investments можно было декларировать доход с дивидендов иностранных эмитентов, предлагаю и вам отправить похожий запрос в поддержку. Брокерские отчеты раньше тоже были только в *.pdf, но люди просили - и они в итоге добавили *.xlsx, который несравнимо лучше с точки зрения парсинга.

> Добрый день.
>
> Я являюсь разработчиком https://github.com/KonishchevDmitry/investments, и ко мне приходят клиенты Тинькофф, которые хотят в автоматическом режиме генерировать налоговую декларацию по дивидендам зарубежных эмитентов, но пока что я вынужден им отвечать, что в брокерских отчетах Тинькофф не хватает всей необходимой информации.
> 
> Сейчас, если дивиденд поступил от зарубежного эмитента (СПБ биржа), в брокерском отчете виден только результирующий размер за вычетом налога (обычно 10%, но может быть и другой), и по данной информации невозможно понять, сколько еще нужно доплатить. Я знаю, что можно скачать Справку о доходах за пределами РФ, и там эта информация должна быть, но данная справка доступна только в pdf-формате, который очень плохо подходит для автоматизированного парсинга (в отличие от *.xslx, в котором можно скачать брокерские отчеты).
> 
> Не могли бы вы добавить в брокерский отчет информацию о изначальном размере дивиденда? Эту информацию вполне можно было бы добавить в колонку "Примечание" - там, где сейчас указывается название эмитента. Ну или хотя бы сделать возможным скачать Справку о доходах за пределами РФ в *.xslx-формате.
> 

> Здравствуйте!
> 
> Я передал разработчикам, чтобы рассмотрели возможность добавить формат xslx для справки с расшифровкой иностранных дивидендов и добавить в брокерский отчет информацию о изначальном размере дивиденда.
> 
> Спасибо, что помогаете улучшать наш сервис!

**Comment by ibarchenkov** [comment]
Сейчас можно запросить "Справку о доходах за пределами РФ" в формате .xlsx через поддержку Тинькова. Не знаю, почему они до сих пор не добавили кнопку в веб интерфейсе или приложении.

**Comment by KonishchevDmitry** [comment]
А, ну в таком случае - если кто-нибудь пришлет мне свой отчет и эту справку, то я готов попробовать поддержать ее.

**Comment by ibarchenkov** [comment]
[tinkoff_dividends_report.xlsx](https://github.com/KonishchevDmitry/investments/files/6021184/tinkoff_dividends_report.xlsx)

**Comment by KonishchevDmitry** [comment]
Спасибо. А можете прислать еще и отчет за все время его существования? Не обязательно сюда, публично - можно мне на konishchev@gmail.com. Только сопоставив одно с другим, можно будет хоть с какой-то уверенностью сказать, что оно будет работать правильно.

Там довольно много нюансов. К примеру, в #21 я столкнулся с довольно большим количеством проблем, а также выяснилось, что почему-то по части российских эмитентов Тинькофф удерживает меньше 13% налога, и автору так и не удалось добиться от поддержки внятного ответа с описанием причины.

Я вот, к примеру, совсем не уверен что наименование эмитентов и даты выплаты в этой бумажке будут всегда совпадать с соответствующими записями в брокерском отчете.

**Comment by AndreySmirdin** [comment]
Подскажите нет ли пока новостей по этой задаче? Тоже очень жду такой функционал!

**Comment by KonishchevDmitry** [comment]
@AndreySmirdin, пока что нет, т. к. пока никто не прислал мне комбинацию отчет + справка в xls, а делать поддержку вслепую не хотелось бы - пока что я стараюсь реализовывать что-либо только в том случае, если мне удается лично провалидировать результат.

**Comment by ibarchenkov** [comment]
@AndreySmirdin, a написал скрипт, который принимает csv таблицу с выгрузкой по дивидендам от Тиньков (можно запросить в техподдержке) и с помощью Chrome driver заполняет в личном кабинете на сайте налоговой форму НДФЛ-3. То есть скрипт в веб интерфейсе создаёт источники доходов, кликает кнопочки и вводит данные. Потом можно выборочно проверить полученный результат и при необходимости вручную ввести другие источники доходов перед отправкой в налоговую. Если нужно, могу выложить в публичный репозиторий и написать инструкцию как пользоваться.

**Comment by aryadev** [comment]
> 
> 
> Если нужно, могу выложить в публичный репозиторий и написать инструкцию как пользоваться.

@ibarchenkov Если не затруднит.

**Comment by ibarchenkov** [comment]
https://github.com/ibarchenkov/ndfl_dividents

К сожалению, чтобы воспользоваться скриптом необходимо установить кучу зависимостей. Я не хочу предоставлять эту услугу как веб сервис, чтобы не собирать персональные данные. Я подумаю и постараюсь упростить процесс запуска на локальной машине. Может в докер упаковать...

**Comment by KonishchevDmitry** [comment]
Добавил поддержку в 3.7.0.
