### ISSUE TITLE
Проблема с парсингом дивидендов для RDS B

### ISSUE THREAD

**Issue by President** [KonishchevDmitry/investments#28]
Похоже что не парсятся строки когда у символа в имени есть пробел:
E: Error while reading ... broker statement: Failed to parse ("Dividends", "Data", "USD", "2020-06-22", "RDS B(US7802591070) Cash Dividend USD 0.32 per Share (Ordinary Dividend)", "48") record: Unexpected dividend description: "RDS B(US7802591070) Cash Dividend USD 0.32 per Share (Ordinary Dividend)".

**Comment by KonishchevDmitry** [comment]
А как у вас эта акция выглядит, к примеру, в `Open Positions`? Там тоже `RDS B` или все-таки `RDS-B`?

**Comment by President** [comment]
в отчетах выгружается как "RDS B"

**Comment by KonishchevDmitry** [comment]
Сможете прислать мне вывод `grep RDS *.csv`?
