### ISSUE TITLE
Не поддерживаются переименования инструментов

### ISSUE THREAD

**Issue by President** [KonishchevDmitry/investments#29]
Вот еще такая ошибка возникает:
E: Calculated open positions don't match declared ones in the statement: CBL PRD: 500 vs 0.

Вероятно вследствие переименования инструмента "CBL PRD" в "CBLDQ" и такая операция в приложении не правильно обрабатывается.

**Comment by President** [comment]
И аналогичная ситуация с инструментом "CTL" - он тоже был переименован в "LUMN"

**Comment by KonishchevDmitry** [comment]
Оно даже без корпоративных действий переименовалось?

Пришлите мне, пожалуйста, свои отчеты на konishchev@gmail.com (можно обезличить перед отправкой). Судя по количеству тикетов, которые вы завели, там довольно много работы, и гораздо проще и надежнее делать поддержку чего-то нового, имея реальный отчет на руках, об который потом можно провалидировать результат, что все в итоге сходится до копейки. Иначе мне придется гадать и делать предположения относительно реального содержимого в отчете, а это может привести к ошибкам в расчетах.

**Comment by titov-vv** [comment]
CBL -> CBLDQ скорее всего без корпоративного действия произошло. Это для потенциальных банкротов на Nasdaq и IB не утруждает по ним отдельное корпоративное действие делать (при этом ISIN/CUSIP остаются прежние). Я уже прилично таких случаев видел.
CTL->LUMN вроде с корпоративным действием был. Могу утончить, если нужно.

**Comment by KonishchevDmitry** [comment]
@titov-vv, спасибо за информацию. Значит, видимо, придется костылить ручное переименование.
Если есть пример корпоративного действия с переименованием, буду благодарен.

**Comment by titov-vv** [comment]
@KonishchevDmitry, заслал в почту тебе.

**Comment by KonishchevDmitry** [comment]
А ведь если ISIN остается прежним, то наверное можно вычислить факт переименования по `Financial Instrument Information` - там ведь тогда по идее будут оба символа с одним и тем же ISIN.

@President, сможете прислать мне вывод `grep CBL *.csv`?

**Comment by Bounz** [comment]
Тоже столкнулся с переименованиями...
Досыпал новых файлов отчетов к старым и получил вот такое:
```
Alexander@investments[master]$ investments show ib
E: Unable to find quotes for following symbols: CHAP, LK, HMI.
```
При этом `CHAP`обанкротились и были делистингованы, `LK` тоже ушли с биржи в pink pages и теперь торгуются как `LKNCY`,`HMI` переименовались в `ZEPP`.
При этом не ясно, как стоит поступать с такими историями, т.к. в новых отчетах IB инструменты уже с новыми тикерами, но по старым отчетам система пытается добыть данные, а данных нет...

**Comment by KonishchevDmitry** [comment]
@Bounz,

1. Виден ли в вашем случае факт переименования в `Financial Instrument Information` или в `Corporate Actions`?
2. finnhub.io, с которого я подтягиваю текущие котировки, отдает их для LKNCY и ZEPP, но вот CHAPQ - нет (видимо из-за того, что он OTC). Так что с двумя из трех вроде теоретически работать в текущем виде можно.
3. Если научить программу определять переименования, то проблемы будут только с CHAPQ (если не менять текущего поставщика котировок). При этом если его продать, то проблема уйдет. Для закрытых позиций никаких данных не ищется - только расчитывается FIFO с ценами из отчета и обрабатываются корпоративные действия.
4. Прямо сейчас в моменте можете пофиксить автозаменой старых названий на новые.
5. Сможете поделиться своими отчетами?

**Comment by Bounz** [comment]
Прошу прощения за долгий ответ.
1. Видимо когда в `Financial Instrument Information` тикеры через запятую указаны - это и есть переименование:
```
Financial Instrument Information,Data,Stocks,"LKNCY, LK",LUCKIN COFFEE INC - ADR,365306774,US54951L1098,PINK,1,ADR,
```
При этом Investments падает на этой строчке явно не ожидая запятую в названии тикера:
```
E: Error while reading "/Users/Alexander/.investments/Brokerage/ibkr/U_20200102_20201231.csv" broker statement: Failed to parse ("Financial Instrument Information", "Data", "Stocks", "LKNCY, LK", "LUCKIN COFFEE INC - ADR", "365306774", "US54951L1098", "PINK", "1", "ADR", "") record: Got a stock symbol with an unsupported format: "LKNCY, LK".
```
2. Про Chaparral Energy Inc: да, к сожалению finnhub не знает про них ничего ни по тикеру `CHAP`, ни `CHAPQ`. При этом я его продал в 2020м как раз, когда они собрались подавать заявку на процедуру банкротства. Но для отчета `tax-statement` наличие инфы с finnhub не критично, так что живем, ура!

**Comment by KonishchevDmitry** [comment]
Посмотрел я тут на те переименования, которые есть в моем распоряжении. Там столько разных ситуаций... Переименование со сменой ISIN, без смены ISIN; если были торговые операции, то в Financial Instrument Information скорее всего будет отражен факт переименования, если нет - то нет, и т. п. Посмотрел на все это, взгрустнул - и решил, что жизнь слишком коротка, чтобы тратить ее на всевозможные причуды в брокерских отчетах. :) Уж больно много там надо гадать по каким-то косвенным признакам.

Поэтому в итоге, как и планировал изначально, сделал возможность задания корпоративного действия вручную в конфиге. К примеру, для CBL нужно указать вот такое:
```yaml
corporate_actions:
  - date: 03.11.2020
    symbol: CBL
    type: rename
    new_symbol: CBLAQ
  - date: 03.11.2020
    symbol: CBL-PRD
    type: rename
    new_symbol: CBLDQ
```

Доступно в 2.15.0.

**Comment by xkrt** [comment]
@KonishchevDmitry с новым годом!

Не получается обработать переименование бумаги:
```
$ investments sync ib
E: Error while reading "/Users/xkrt/Brokerage/Interactive Brokers/Statements/activity-2021.csv" broker statement: Failed to parse ("Corporate Actions", "Data", "Stocks", "USD", "2021-03-05", "2021-03-04, 20:25:00", "TRXC(US89366M3007) CUSIP/ISIN Change to (US04367G1031) (ASXC, ASENSUS SURGICAL INC, US04367G1031)", "5", "0", "0", "0", "") record: Unsupported corporate action: "TRXC(US89366M3007) CUSIP/ISIN Change to (US04367G1031) (ASXC, ASENSUS SURGICAL INC, US04367G1031)".
```

В конфиг добавил строчки `corporate_actions`, не помогло:
```
portfolios:
  -  name: ib
     broker: interactive-brokers

    # Sometimes stocks are renamed without any corporate action (see https://github.com/KonishchevDmitry/investments/issues/29)
    # Manual corporate action specification solves the issue.
    corporate_actions:
      - date: 05.03.2021
        symbol: TRXC
        type: rename
        new_symbol: ASXC
```

Версия 4.0.0.
Могу выслать activity statement на почту, если надо.

**Comment by KonishchevDmitry** [comment]
@xkrt, а вы при этом удалили из отчета строку, содержащую корпоративное действие (`TRXC(US89366M3007) CUSIP/ISIN Change to (US04367G1031) (ASXC, ASENSUS SURGICAL INC, US04367G1031)`)?

**Comment by xkrt** [comment]
@KonishchevDmitry не подумал об этом🤦
После удаления строк про корпоративное действие всё сработало, спасибо!
