### ISSUE TITLE
E: "/Users/{username}/Brokerage/Interactive/Statements/" doesn't contain any broker statement.

### ISSUE THREAD

**Issue by pltnm239** [KonishchevDmitry/investments#32]

**Comment by pltnm239** [comment]
При запуске команды `investments analyse ib` одна и та же ошибка: 
`E: "/Users/{username}/Brokerage/Interactive/Statements/" doesn't contain any broker statement.`

Конфиг используется по шаблоны, выгрузку делал по инструкции.

В чем может быть проблема?

**Comment by KonishchevDmitry** [comment]
Вот по [этой](https://github.com/KonishchevDmitry/investments#t2-trading-mode) инструкции? Эти отчеты несут исключительно информацию о T+2 settle date - они только дополняют информацией основные отчеты, и это опциональная вещь.

Отчеты, которые ищет программа - это стандартный Activity Statement в *.csv (Reports -> Statements -> Activity).
