### ISSUE TITLE
Can't specify config path

### ISSUE THREAD

**Issue by Rom888** [KonishchevDmitry/investments#35]
```
$ ls /media/t/fin/investments-data
config.yaml

$ investments -c /media/t/fin/investments-data tax-statement ib
E: Error while reading "/home/rom/investments-data": No such file or directory (os error 2).
```
The path in the error message does not match the specified path.

**Comment by KonishchevDmitry** [comment]
It's not configuration file reading error. You have `/home/rom/investments-data` or `~/investments-data` broker statements path specified in `/media/t/fin/investments-data/config.yaml`.
