### ISSUE TITLE
E: Failed to process dividend income: ... EUR currency is not supported yet.

### ISSUE THREAD

**Issue by Rom888** [KonishchevDmitry/investments#38]
```
$ investments --config /media/t/fin/investments-data tax-statement ib 2020 /media/t/fin/investments-data/tax-return-2020.dc0
W: The broker statement misses trade settle date information. First occurred trade - EXH4d at 16.04.2020. All calculations for such trades will be performed in T+0 mode.
E: Failed to process dividend income: Unable to add EXH4 dividend from 15.07.2020 to the tax statement: EUR currency is not supported yet.
```
:(

**Comment by KonishchevDmitry** [comment]
`*.dcX` - закрытый формат, поэтому приходится каждый год формировать фейковую декларацию со всеми поддерживаемыми операциями и в unit-тестах проверять, что ничего не изменилось, и я сгенерю точно такие же данные. А т. к. набивать это все приходится руками, то ничего лишнего стараюсь не поддерживать. :)

Добавил поддержку в 2.11.3.

**Comment by Rom888** [comment]
Заработало!
Спасибо, и здорово что функциональность покрыта тестами.
