### ISSUE TITLE
Tax statement and REIT ETF

### ISSUE THREAD

**Issue by Worm** [KonishchevDmitry/investments#39]
Приветствую. Подаю декларацию за 2020 год. При расчете налогов имеется проблема с учетом дивидендов от REIT ETF'ов как пример (VNQ) и расчетом доплаты.

По отчету IB:
13.03 начислен дивиденд 183.51 USD (VNQ)
13.03 удержан налог -18.14 USD (VNQ)

По формируемому отчету командой tax-statement видно учитывается что уплачено только 10.59$ (в отчете -18.14)

   Дата                  Эмитент                Валюта    Сумма    Курс руб.  Сумма (руб)  Налог   Уплачено  Уплачено (руб)  К зачету  К доплате  Реальный доход
13.03.2020  VANGUARD REAL ESTATE ETF (VNQ)       USD      $181.41    74.0274   13,429.31₽  1,746₽    $10.59         783.95₽      784₽       962₽      11,683.36₽

С другими эмитентами всё впорядке, проблема только с VNQ по всем строкам с дивидендами, почему то с отчетом не совпадает

**Comment by Worm** [comment]
Нашел откуда 10.59$. В отчете за 2020 год указано только

13.03 начислен дивиденд 183.51 USD (VNQ)
13.03 удержан налог -18.14 USD (VNQ)

А отчете за 2021 год нашел строки:
Withholding Tax,Header,Currency,Date,Description,Amount,Code
Withholding Tax,Data,USD,2020-03-13,VNQ(US9229085538) Cash Dividend USD 0.6479 per Share - US Tax,18.14,
Withholding Tax,Data,USD,2020-03-13,VNQ(US9229085538) Cash Dividend USD 0.6479 per Share - US Tax,-10.59,

Первая строка значит что они вернули 18.14, а вторая значит что списали 10.59? (это вопрос) И так по всем строкам по дивидентам VNQ за 2020 год. Сначала списывают 10%, а потом на корректировках возвращают и списывают 5.77%?

По REIT, на сколько помню, USA должна удерживать 30% налога вне зависимости от подписания формы W-8BEN

**Comment by KonishchevDmitry** [comment]
> Первая строка значит что они вернули 18.14, а вторая значит что списали 10.59?

Да

> По REIT, на сколько помню, USA должна удерживать 30% налога вне зависимости от подписания формы W-8BEN

Сходу не скажу, но кажется нет. Деталей, к сожалению, не помню. Возможно это справедливо только для самих акций, но не для ETF на них.

Про корректировки мне поддержка в свое время ответила следующее:
> Every year IB has to adjust the 1042 withholding (i.e. withholding on US dividends paid to non-US accounts) to reflect dividend reclassifications. This is typically done in February the following year. As such, the majority of these adjustments are refunds to customers. The typical case is when IB's best information at the time of paying a dividend indicates that the distribution is an ordinary dividend (and therefore subject to withholding), then later at year end, the dividend is reclassified as Return of Capital, proceeds, or capital gains (all of which are not subject to 1042 withholding).

> Не совсем понятно как сделать правильно. В отчете сформированном за 2020 год получается не сходятся суммы списанные по налогу US, в отчете IB списано больше, чем по расчетной таблице tax-statement. Получается что бы цифры сошлись надо дополнительно подавать корректировки, которые появились уже в отчете 2021 года... Но я не уверен что налоговик полезет в отчет 2021 года что бы смотреть эти корректировки...

Но, кстати, зато расчеты в tax-statement должны по идее сходиться с 1042-S.

Да, тут действительно довольно спорный момент, и однозначного ответа по крайней мере мне [найти не удалось](https://www.banki.ru/forum/?PAGE_NAME=message&FID=21&TID=377500&MID=8558603#message8558603). Но, если принимать во внимание все детали, кажется, что учитывать их в 2020 все-таки наиболее корректно. Лично я вообще не прикладываю отчеты к декларации - как раз из-за таких вот моментов - можно только запутать инспектора, уж больно много там тонкостей. А если уж все-таки попросят подтверждающие документы - тогда можно прислать вместе со здоровенной пояснительной запиской, в которой можно описать нюансы конкретно вашего отчета.

**Comment by Worm** [comment]
А у Вас "Gross Income" в 1042-S сходится с суммой дивидендов за 2020 год посчитанные программой? 

Смотрю свой 1042-S, да верно, с учетом корректировок 2021 года, сошлась сумма уплаченного налога в US, однако сумма Gross Income в 1042-S указана меньше, чем сумма всех дивидендов посчитанная программой за этот же период.

При этом Federal tax withheld = 10% от Gross Income. Получается что помимо корректировок на удержанный налог должна быть корректировка и на поступления дивидендов - меньше дивидендов, меньше удержанный налог.

**Comment by KonishchevDmitry** [comment]
Если сложить все числа в Gross Income, то сходится с небольшой погрешностью, которая, возможно, возникает из-за округлений до целого в различных местах.

У меня 1042-S состоит из 12 страниц (4 дохода, для каждого 3 копии):
* Income code 06, Exemption code 10, Tax rate 10.0
* Income code 36, Exemption code 02, Tax rate 0.0
* Income code 37, Exemption code 02, Tax rate 0.0
* Income code 01, Exemption code 05, Tax rate 0.0

В прошлые года тоже все сходилось с разумной погрешностью.

Корректировок на размер дивидендов вроде не бывает - сколько выплатили, столько и будет - вроде нет причин, почему оно может скорректироваться.

Тут, конечно, надо смотреть на конкретно ваш случай. Просто фантазирую: к примеру, может если у вас был какой-нибудь stock dividend, а не обычный, то оно в 1042-S не входит в Gross Income.

**Comment by KonishchevDmitry** [comment]
Написал документацию с основными моментами, касающимися взаимодействия с налоговой, включая данный вопрос - https://github.com/KonishchevDmitry/investments/blob/master/docs/taxes.md#dividend-reclassifications

**Comment by KonishchevDmitry** [comment]
@Worm, возможно вот ответ на ваш вопрос - https://www.banki.ru/forum/?PAGE_NAME=message&FID=21&TID=379285&MID=8570936#message8570936:
> Она не включает дивиденды где налоги не были удержаны совсем.
