### ISSUE TITLE
Не линкуется migrations_macros

### ISSUE THREAD

**Issue by nikitabuida** [KonishchevDmitry/investments#4]
При сборке по инструкции выдает:

` = note: LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'

error: aborting due to previous error
error: could not compile `migrations_macros`.`

MS VS SDK установлен, но может нужно еще что-то или дополнительные пути прописать?

**Comment by KonishchevDmitry** [comment]
Для Ubuntu я бы вам посоветовал `apt install libsqlite3-dev`, для MacOS - `brew install sqlite`, а вот как это принято делать в Windows - понятия не имею. :)

Я под Windows ни разу в своей жизни ничего не писал, да и как пользователь ее больше 10 лет уже не использовал (запуск программы налоговой декларации раз в год в виртуалке - не в счет), поэтому и как целевую платформу ее никогда не рассматривал (ну и не только поэтому).

Вам явно не хватает devel-пакета sqlite, с которым можно было бы слинковаться. Первая ссылка из Google - https://github.com/jgallagher/rusqlite#user-content-notes-on-building-rusqlite-and-libsqlite3-sys:

> Installing the sqlite3 development packages will usually be all that is required, but
  the build helpers for [pkg-config](https://github.com/alexcrichton/pkg-config-rs)
  and [vcpkg](https://github.com/mcgoo/vcpkg-rs) have some additional configuration
  options. The default when using vcpkg is to dynamically link,
  which must be enabled by setting `VCPKGRS_DYNAMIC=1` environment variable before build.
  `vcpkg install sqlite3:x64-windows` will install the required library.

Возможно это вам поможет.

**Comment by nikitabuida** [comment]
Воспользовался вашим советом и побилдил на Убунту. Кстати вылезла та же ошибка и пришлось поставить libsqlite3-dev, после чего все прошло без проблем. Может это стоит указать в инструкции.

В винде тоже пытался, но там действительно как-то все слишком загадочно.

Спасибо!
