### ISSUE TITLE
investments metrics: E: Error while reading "/home/rom/Brokerage/Открытие/Отчеты Брокера": No such file or directory (os error 2).

### ISSUE THREAD

**Issue by Rom888** [KonishchevDmitry/investments#41]
Пытаюсь сгенерировать метрики:
```
$ investments metrics ./metrics.txt
E: Error while reading "/home/rom/Brokerage/Открытие/Отчеты Брокера": No such file or directory (os error 2).
```
У меня пока IB только, и нет открытия брокера и остальных.
Не очень понятно как отключить остальных брокеров в этом случае?
Пробовал подсунуть пустую директорию, но не помогает, требует отчеты :)

**Comment by KonishchevDmitry** [comment]
Честно говоря, не понял сути проблемы. Вы же, насколько я понимаю, просто взяли [config-example.yaml](https://github.com/KonishchevDmitry/investments/blob/master/config-example.yaml), в котором они перечислены для примера. Удалите из него все лишнее - и будет работать.

**Comment by Rom888** [comment]
Теперь понятно, просто это было не очевидно.
После удаления лишнего заработало, спасибо!
Теперь другая ошибка: E: Unable to find quotes for following symbols: EXV8d, EXH4d.
Но это уже к этому тикету не относится.
