### ISSUE TITLE
Поддержка не торгуемого тикера

### ISSUE THREAD

**Issue by antonzaytsev** [KonishchevDmitry/investments#44]
Здравствуйте Дмитрий. Спасибо за ваш труд и интересную консольную утилиту.

При импорте данных появилась ошибка "Unable to find quotes for following symbols: CELG".
Дело в том что CELG тикер больше не торгуется, компания была куплена другой.

Как добавить возможность обработки такого случая?

**Comment by KonishchevDmitry** [comment]
Добрый день.

А что конкретно с ней произошло? Компания не торгуется, но позиция у вас открыта? Судя по ошибке, никаких корпоративных действий относительно нее в отчете нет - иначе бы парсинг свалился раньше. Т. е., по информации из отчета у вас эта позиция по прежнему открыта.

В общем, нужны подробности. В идеале - с самими отчетами. Ну или хотя бы с выжимкой из них.

**Comment by antonzaytsev** [comment]
@KonishchevDmitry я понял в чем дело. Проблемы в программе скорее всего нет. Дело в том что позиция открыта в 2018 году и закрыта в 2019. Но я оставил отчеты только до 2018 включительно. То есть отчета о закрытии у программы не было. После добавления отчета за 2019 - эта проблема ушла. Спасибо!
