### ISSUE TITLE
Проблема обновления. MacOS

### ISSUE THREAD

**Issue by Worm** [KonishchevDmitry/investments#5]
Добрый день! 

При обновлении приложении возникла проблема. Вытянул изменения с репы через `git pull`, попытался запустить из папки `cargo install --path . --bin investments --force` однако вывалилась ошибка:

---------------------------------------------------------

error: `/Users/worm/investments` is not a crate root; specify a crate to install from crates.io, or use --path or --git to specify an alternate source

Caused by:
  failed to parse manifest at `/Users/worm/investments/Cargo.toml`

Caused by:
  the `default-run` manifest key is unstable

Caused by:
  feature `default-run` is required

this Cargo does not support nightly features, but if you switch to nightly channel you can add
`cargo-features = ["default-run"]` to enable this feature

---------------------------------------------------------
Пробовал поставить nightly и добавить строку `cargo-features = ["default-run"]` в начало файла Cargo.toml. Однако так и не смог пересобрать.

По итогу удалил строку `default-run = "investments"` из файла Cargo.toml, билд пошел но в итоге снова вывалило кучу ошибок:

error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
error: Could not compile `smallvec`

Help pls

**Comment by Worm** [comment]
Sorry. Разобрался нужно было обновить `rustup update`, после чего сборка приложения выполнилась без ошибок. Всё работает, спасибо за приложение!

**Comment by Bsplesk** [comment]
need to add binary builds (x86/x64 - releases) for windows users.
example: https://github.com/morbac/xmltools/releases
