### ISSUE TITLE
E: Unable to find quotes for following symbols: FIXP

### ISSUE THREAD

**Issue by maxvipon** [KonishchevDmitry/investments#52]
FIXP — тикер компании FixPrice на московской бирже
https://www.moex.com/ru/issue.aspx?board=TQBR&code=FIXP

но его нет ни на `finnhub.io`, ни на `twelvedata.com`

**Comment by KonishchevDmitry** [comment]
С Московской биржи я котировки беру, но пока только с `TQTF` ради FinEx'а. У них там такое количество этих режимов торгов, что в свое время даже не стал разбираться - взял тот, который нужен был лично мне - до тех пор, пока не придет кто-то и не попросит еще. Все неглядя добавлять дорого (в плане количества запросов к API) + там будет пересечение по символам (торги в разных валютах и пр.), которое сходу не очень понятно как разруливать - так что неглядя добавлять все подряд тоже как-то не хочется.

`TQBR` наверное не должно быть проблем добавить.

**Comment by KonishchevDmitry** [comment]
Добавил в 2.15.2.

**Comment by maxvipon** [comment]
Всё ок. Спасибо!
