### ISSUE TITLE
Проблема с формированием декларации 2021

### ISSUE THREAD

**Issue by IlyaKarpelyuk** [KonishchevDmitry/investments#57]
Приветствую Дмитрий! Еще раз спасибо большое за прогамму и с новым годом!

Не выходит наполнить отчет в формате программы "Декларация 2021"

При попытке наполнить файл "blank.dc1" вылазет следующая ошибка, см. скриншот.
При том что сам tax-statement за 2021 год (без наполнения файла) формирует корректно, без ошибок.
Файл blank.dc1 формировал по инструкции.
Так же, корректно наполняются и файлы "*.dc0" для "Декларации 2020"

Версия программы investment - 3.11.1, версия "Декларация 2021" - 1.0.0 от 30.12.2021
Сам файлик blank.dc1 выслал по почте.

![image](https://user-images.githubusercontent.com/65602043/147849064-ec2efef9-724f-430a-ba41-adc1c33cc5a1.png)

**Comment by KonishchevDmitry** [comment]
Добрый день!

Да, спасибо - это ожидаемо. Как вы можете видеть, программа сама вам пишет, что пока поддерживает только формат 2020 года.

Программу "Декларация" Налоговая выпускает в последний рабочий день года, и поэтому это всегда сюрприз под новый год - что они там наменяют, и заранее не подготовишься. Я вчера почти под бой курантов сделал базовую поддержку (https://github.com/KonishchevDmitry/investments/commit/1d950fc5b3b5557260ba8cc4294c73c60d7ef28b), но пока не релизил, т. к. по-хорошему надо бы сделать еще дополнительные изменения: сейчас я все дивиденды от американских брокеров [декларирую со страной дохода США](https://github.com/KonishchevDmitry/investments/blob/master/docs/taxes.md#foreign-income-jurisdiction) - и это выглядело нормально до текущего момента, но в новой форме 3-НДФЛ теперь разделили страну дохода на две: страна источника дохода и страна получения дохода - и теперь уже мой текущий подход выглядит уже неправильным. Для российских брокеров у меня вся необходимая для этого информация уже собирается из отчетов, а для американских - пока нет.

Поэтому:
1. Если хочется проверить заранее, как справится программа с вашими отчетами, то можно посмотреть пока на текущую реализацию - `git clone https://github.com/KonishchevDmitry/investments.git && cd investments && cargo install --path . --force`.
2. Спешить и формировать уже чистовой вариант декларации в любом случае [пока еще рано](https://github.com/KonishchevDmitry/investments/blob/master/docs/taxes.md#dividend-reclassifications).
3. Я думаю, что смогу сделать все необходимые изменения за новогодние праздники - и тогда выпущу новую версию и отпишусь сюда.

**Comment by IlyaKarpelyuk** [comment]
Спаибо большое, будем ожидать! :)

**Comment by KonishchevDmitry** [comment]
Зарелизил. Теперь можно пользоваться.
