### ISSUE TITLE
Unexpected dividend description with IB

### ISSUE THREAD

**Issue by Bounz** [KonishchevDmitry/investments#6]
Hi Dmitry!

Thank you for such interesting and useful application (especially `tax-statement` part)!

During import IB statements I faced an issue "Unexpected dividend description" when report has lines like this:
```
Dividends,Data,USD,2019-04-15,UNIT(US91325V1089) Payment in Lieu of Dividend (Ordinary Dividend),0.35
Withholding Tax,Data,USD,2019-04-15,UNIT(US91325V1089) Payment in Lieu of Dividend - US Tax,-0.03,
```

To fix it I've changed regular expressions from
```
r"^(?P<issuer>[A-Z]+) ?\([A-Z0-9]+\) Cash Dividend ").unwrap();
```
to
```
r"^(?P<issuer>[A-Z]+) ?\([A-Z0-9]+\) (?:Cash Dividend |Payment in Lieu of Dividend )").unwrap();
```
but after that I though that maybe we should change them like this:
```
r"^(?P<issuer>[A-Z]+) ?\([A-Z0-9]+\) ").unwrap();
```
and don't check message at all?
What do you think @KonishchevDmitry?

**Comment by KonishchevDmitry** [comment]
Hi! Thanks for the report.

I intentionally used strict regular expressions here to be sure I won't miss something which I haven't thought of yet, but looking at all variants in current unit tests plus your one, I think you're right and it's time to generalize this place.

Fixed.
