### ISSUE TITLE
Запуск билда 4.3.1 на Windows

### ISSUE THREAD

**Issue by steg-kc** [KonishchevDmitry/investments#61]
Привет! Сразу спасибо за работу, тул выглядит очень многообещающе. Проблема: последний билд Windows 4.3.1 не запускается, проверил на нескольких ПК. Просто ничего не происходит. Если билдить самому по инструкции, та же история. В чем может быть проблема?

**Comment by KonishchevDmitry** [comment]
А как именно вы его запускаете: через терминал или простым двойным кликом по бинарнику? Предполагается запуск из терминала, т. к. интерфейс - консольный.

Скачал только что, распаковал - запускается (Windows 10):
![Run on Windows](https://user-images.githubusercontent.com/217795/152484103-1fa180fb-71c6-4068-8cd5-3b47c78cc031.png)

**Comment by steg-kc** [comment]
Спасибо, не догадался. Буду изучать!

**Comment by KonishchevDmitry** [comment]
Рекомендую только поставить [Windows Terminal](https://aka.ms/terminal), а не пользоваться стандартным [cmd.exe](https://ru.wikipedia.org/wiki/Cmd.exe) - он уж слишком устарел, даже терминальные команды управления цветом символов до сих пор не поддерживает.
