### ISSUE TITLE
Ошибка при загрузке нового Activity statement

### ISSUE THREAD

**Issue by antonrubtsov** [KonishchevDmitry/investments#63]
investments analyse ib

E: Error while reading "/home/test/investments/flex/reports/U********_20210104_20211231.csv" broker statement: Failed to parse record: Got an unexpected "DataDiscriminator" field value: "Summary".

Может есть быстрый фикс?

**Comment by antonrubtsov** [comment]
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/747577/155371060-28ecca3d-5ea4-4635-bc48-d14b313fc683.png">

**Comment by KonishchevDmitry** [comment]
Запустите пожалуйста с версией 4.4.1 - я там в сообщение добавил номер строки. У меня такое ощущение, что проблема в другом месте (секция `Trades`?) - не там, где вы показали.

**Comment by antonrubtsov** [comment]
Огромное спасибо за содействие. И прошу прощения за дурацкие вопросы.
Проблема была действительно в версии приложения. 
Отныне в докере буду запускать.
