### ISSUE TITLE
Unsupported corporate action: subscribable rights issue

### ISSUE THREAD

**Issue by revic50** [KonishchevDmitry/investments#67]
Дмитрий, здравствуйте!

Спасибо за подаренную надежду автоматизации декларации по дивидендам) Пока отчет сгенерить не получается, ошибка на прикрепленном скриншоте. Отчет формировал как Activity Statement, так и Custom Statement в соответствии с рекомендациями. Ошибка одна и та же (только на разных строках).

Заранее благодарю за советы.
![issue](https://user-images.githubusercontent.com/104514720/165552739-9bb53797-fe5d-49a3-b040-e3566f9756c9.jpg)

**Comment by KonishchevDmitry** [comment]
Кажется, это корпоративное действие ни на что не влияет, если вы им не воспользовались (см. https://github.com/KonishchevDmitry/investments/issues/64#issuecomment-1086974284). Попробуйте его просто удалить - пойдет дальше или на чем-то другом свалится?

**Comment by revic50** [comment]
Удалил, пошло! Спасибо огромное за Ваш труд!
