### ISSUE TITLE
Ошибка при чтении отчетов брокера Открытие для фондового рынка Московской биржи - возмещение за депозитарий

### ISSUE THREAD

**Issue by nikitabuida** [KonishchevDmitry/investments#68]
Добрый день!
investments tax-statement open-moex 2021
Вылезла еще одна ошибка:

E: Error while reading "Broker_Report_177023_FR_MB_2021.xml" broker statement: Unable to determine cash flow type by its description: "Возмещение за депозитарные услуги счет услуги вышестоящего Депозитария за хранение ЦБ наим. ЦБ:GLOBALTRANS-GDR, ISIN US37949E2046 от 05.11.2021 НКО АО НРД ".

**Comment by KonishchevDmitry** [comment]
Добрый день! Спасибо, поддержал.

**Comment by nikitabuida** [comment]
> Добрый день! Спасибо, поддержал.

Большое спасибо!
