### ISSUE TITLE
Проблема при установке из за нехватки прав на subomule investments-testdata.git

### ISSUE THREAD

**Issue by coodix** [KonishchevDmitry/investments#7]
Проблема при установке из за нехватки прав на subomule investments-testdata.git:

`➜  investments git:(master) cargo install --git https://github.com/KonishchevDmitry/investments.git --bin investments --force
    Updating git repository `https://github.com/KonishchevDmitry/investments.git`
error: failed to update submodule `testdata`

Caused by:
  failed to fetch submodule `testdata` from git@konishchev.ru:investments-testdata.git

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

Caused by:
  no authentication available`

**Comment by KonishchevDmitry** [comment]
Ох, внезапно. :) Видимо придется вернуть инструкцию на ручное клонирование репозитория.

Если сделать
```
$ git clone https://github.com/KonishchevDmitry/investments.git
$ cd investments
$ cargo install --path . --bin investments --force
```
то должно работать.

Сегодня вечером проверю и обновлю инструкцию.

Спасибо!

**Comment by coodix** [comment]
Ручная установка сработала успешно, спасибо!

А репозиторий investments-testdata.git хранит тестовые данные, если я правильно понимаю? Там у вас какие-то реальные данные?

**Comment by KonishchevDmitry** [comment]
Да - там мои реальные отчеты и налоговые декларации. Против них гоняются unit-тесты + [регрессионные тесты](https://github.com/KonishchevDmitry/investments/blob/master/regression_tests/rt.rt) на все команды.
