### ISSUE TITLE
[Tinkoff] Got an unexpected tax refund

### ISSUE THREAD

**Issue by maxvipon** [KonishchevDmitry/investments#71]
```
$ investments sync tinkoff
E: Got an unexpected tax refund for 2022 year on 29.01.2022: it's bigger then withheld amount by 76₽.
```

Пример отчёта: [broker-report-2022-01-01-2022-02-28.xlsx](https://github.com/KonishchevDmitry/investments/files/10343206/broker-report-2022-01-01-2022-02-28.xlsx)

**Comment by KonishchevDmitry** [comment]
Правильно ли я понимаю, что вы что-то продали в 2021-ом -> вывели деньги -> у вас из них удержали налог, а затем в том же 2021-ом что-то продали с убытком - и вот 2022-ом вам вернули излишне удержанный налог?

**Comment by maxvipon** [comment]
Нет. Я ничего не продавал, только покупал.

**Comment by KonishchevDmitry** [comment]
А что это тогда такое? :) Это ведь, насколько я понимаю, возврат излишне удержанного налога, который вероятнее всего был удержан в 2021 году. У вас были какие-то удержания в 2021? Налог мог быть, к примеру, от дохода с продажи валюты или с дивидендов.

**Comment by maxvipon** [comment]
Если честно, мне сложно предположить. Я могу попробовать сделать выгрузку за все время и поискать в ней. Я пробовал смотреть за год, но ничего путного не нашел.

**Comment by maxvipon** [comment]
Так ничего и не нашёл. Просто удалил строку tax refund из отчёта и засинкалось.
