### ISSUE TITLE
Failed to get quotes from FinEx

### ISSUE THREAD

**Issue by maxvipon** [KonishchevDmitry/investments#73]
```
$ investments show tinkoff
E: Failed to get quotes from FinEx: Failed to get quotes from https://api.finex-etf.ru/v1/fonds/nav.xlsx: Invalid price (0): The value doesn't comply to the specified restrictions.
```

[Фонд FXRB от FinEx лишился активов и будет закрыт](https://journal.tinkoff.ru/news/fxrb-rip/)

**Comment by KonishchevDmitry** [comment]
А сами акции из отчётов брокера не пропали? Тут по идее наверное нужно скорее добавлять поддержку корпоративного действия по делистингу.

**Comment by maxvipon** [comment]
В списке акций в приложении FXRB нет, но в отчетах-то они фигурировали какое-то время.

**Comment by KonishchevDmitry** [comment]
А они абсолютно молча пропали (как это обычно бывает в Тинькове со всеми корпоративными действиями) или с каким-то упоминанием/списанием в отчёте?

**Comment by maxvipon** [comment]
За 2022:
<img width="1405" alt="image" src="https://github.com/KonishchevDmitry/investments/assets/871596/a0294177-e47a-4a30-b867-a8a708f06dc8">

За 2023:
<img width="1331" alt="image" src="https://github.com/KonishchevDmitry/investments/assets/871596/38d32a67-edc8-4fb7-a5aa-b3304b6fe038">
— тут есть списание FXRB.

Теперь ошибка такая:
```
$ investments sync tinkoff
E: Calculated open positions don't match declared ones in the statement: FXRB: 14200 vs 0.
```
