### ISSUE TITLE
There is no manual or help on the tax_remapping syntax

### ISSUE THREAD

**Issue by IlyaKarpelyuk** [KonishchevDmitry/investments#74]
Hello, Dmitry!

Thank you for great progress of the investments app.

I am facing the following problem while using the investment; see screenshot.
The manual at the address http://bit.ly/investments-ib-tax-remapping does not give a specific syntax on how to execute tax remapping.
Could you please describe in more details in user manual/readme file.

![image](https://user-images.githubusercontent.com/65602043/212707763-da9cdc89-393a-44b2-b054-6b05bc8f93cc.png)

**Comment by KonishchevDmitry** [comment]
Hi! It's configuration option - not command line one. So it should be specified in the configuration file. Here is an example - https://github.com/KonishchevDmitry/investments/blob/782b8c37baf4d45f3f294956aec21717a6270fbf/docs/config-example.yaml#L15-L19

**Comment by IlyaKarpelyuk** [comment]
Thank you for your quick response, Dmitry!
However, my tax_remapping throws an error:

![image](https://user-images.githubusercontent.com/65602043/213146358-d0e72992-3da0-4bc9-9846-09c814a5cf71.png)


There is my config file:

![image](https://user-images.githubusercontent.com/65602043/213146595-6173dbcc-89e2-4146-8f8c-9c4330b2eff6.png)

Do you have any ideas how I can fix it, maybe I missed something somewhere?

**Comment by KonishchevDmitry** [comment]
It's hard to debug such things without real statement on hands, but, from the error, it looks like there is no tax with such description and date in the statement. What `grep -E '^(Dividends|Withholding Tax),.*,STOR' *.csv` shows?

P.S.: Looking on the dates you have problem with, I see that you've sent your 2021 tax statement too early, so I'd recommended you to look at recommendations on https://github.com/KonishchevDmitry/investments/blob/master/docs/taxes.md#dividend-reclassifications and generate your final tax statement in march when the broker statement should contain all reclassifications.

**Comment by IlyaKarpelyuk** [comment]
Thank you! 
I will probably do so, I will generate a IB report in March.

**Comment by KonishchevDmitry** [comment]
To not be misunderstood: I recommend to generate **final** tax statement in March, but it's still better to try in January to generate intermediate results (as you do now) - just to be sure that your broker statement is still parsable and to have a time to fix possible issues until March.

**Comment by fughur** [comment]
@KonishchevDmitry God bless you! 2022.02.10 -> 2021.02.05 is worked like a charm!

**Comment by IlyaKarpelyuk** [comment]
Hello, Dmitry!
Unfortunately, the latest 10th march statament does not help to solve the issue.
Do you have any ideas, how this can be solved?

![image](https://user-images.githubusercontent.com/65602043/224330598-33bd5d07-4ede-42c8-8794-b569864a5fc8.png)

**Comment by KonishchevDmitry** [comment]
@IlyaKarpelyuk, text output would be much friendlier than the image to debug such things. ;)

Here is what I see according to https://github.com/KonishchevDmitry/investments/commit/d597ba69ffc3cb9500e68f1285708f539eee694e:

Something old and not interesting to us:
```
Withholding Tax,Data,USD,2020-10-15,STOR(US8621211007) Cash Dividend USD 0.36 per Share - US Tax,3.96,
Withholding Tax,Data,USD,2020-10-15,STOR(US8621211007) Cash Dividend USD 0.36 per Share - US Tax,-3,
```

Original dividends:
```
Dividends,Data,USD,2021-01-15,STOR(US8621211007) Cash Dividend USD 0.36 per Share (Ordinary Dividend),39.6,
Withholding Tax,Data,USD,2021-01-15,STOR(US8621211007) Cash Dividend USD 0.36 per Share - US Tax,-3.96,

Dividends,Data,USD 2021-04-15,STOR(US8621211007) Cash Dividend USD 0.36 per Share (Ordinary Dividend),39.6,
Withholding Tax,Data,USD,2021-04-15,STOR(US8621211007) Cash Dividend USD 0.36 per Share - US Tax,-3.96,

Dividends,Data,USD 2021-07-15,STOR(US8621211007) Cash Dividend USD 0.36 per Share (Ordinary Dividend),39.6,
Withholding Tax,Data,USD,2021-07-15,STOR(US8621211007) Cash Dividend USD 0.36 per Share - US Tax,-3.96,
```

Refunds:
```
Withholding Tax,Data,USD,2021-04-15,STOR(US8621211007) Cash Dividend USD 0.36 per Share - US Tax,3.96,
Withholding Tax,Data,USD,2021-04-15,STOR(US8621211007) Cash Dividend USD 0.36 per Share - US Tax,-3.14,

Withholding Tax,Data,USD,2021-07-15,STOR(US8621211007) Cash Dividend USD 0.36 per Share - US Tax,3.96,
Withholding Tax,Data,USD,2021-07-15,STOR(US8621211007) Cash Dividend USD 0.36 per Share - US Tax,-3.14,
```

Problem refunds:
```
Withholding Tax,Data,USD,2022-01-25,STOR(US8621211007) Cash Dividend USD 0.36 per Share - US Tax,3.96,
Withholding Tax,Data,USD,2022-01-25,STOR(US8621211007) Cash Dividend USD 0.36 per Share - US Tax,-3.14,
```

So I believe that you need:
```yaml
tax_remapping:
  - {date: 2022.01.25, to_date: 2021.01.15, description: STOR(US8621211007) Cash Dividend USD 0.36 per Share - US Tax}
```

**Comment by IlyaKarpelyuk** [comment]
Thank you very much, Dmitry.
I've successfully remapped my problem ticket.
