### ISSUE TITLE
[Tinkoff] Unknown exchange: "ВНБ"

### ISSUE THREAD

**Issue by maxvipon** [KonishchevDmitry/investments#82]
`
$ investments sync tinkoff
E: Error while reading "/Users/maxpon/Brokerage/Тинькофф/Отчеты Брокера/broker-report-2023-07-01-2023-10-31.xlsx" broker statement: Starting from #9 row: [String("D086064952"), Empty, String("CT230829000000210671"), Empty, Empty, Empty, Empty, Empty, Empty, String("29.08.2023"), Empty, Empty, Empty, String("12:38:36"), Empty, Empty, Empty, Empty, String("ВНБ"), Empty, Empty, Empty, Empty, String("Покупка"), Empty, Empty, Empty, Empty, Empty, String("Fix Price Group PLC ORDSHS GDR"), Empty, Empty, Empty, String("US33835G2057"), Empty, Empty, String("434,4995"), Empty, Empty, Empty, Empty, String("RUB"), Empty, Empty, Empty, String("20"), Empty, Empty, Empty, Empty, String("8689,99"), Empty, Empty, Empty, Empty, Empty, String("0"), Empty, Empty, Empty, Empty, String("8689,99"), Empty, Empty, Empty, String("RUB"), Empty, Empty, Empty, Empty, String("3,48"), Empty, Empty, Empty, Empty, Empty, String("RUB"), Empty, Empty, Empty, Empty, Empty, String("0"), Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, String("0"), Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, String("30.08.2023/30.08.2023"), Empty, Empty, Empty, Empty, Empty, String("30.08.2023/30.08.2023"), Empty, Empty, Empty, Empty, String("К"), Empty, Empty, String("ГС"), Empty, Empty, Empty, Empty, Empty, Empty, String("б/н"), Empty, Empty, Empty, String("22.10.2020"), Empty, Empty, Empty, Empty, Empty, String("RVP"), Empty]: Unknown exchange: "ВНБ".
`

<img width="655" alt="image" src="https://github.com/KonishchevDmitry/investments/assets/871596/b9b3fa28-610b-4d3e-9306-4279a19fb375">

<img width="580" alt="Screenshot 2023-11-23 at 15 09 03" src="https://github.com/KonishchevDmitry/investments/assets/871596/66e6bd1d-2175-44a3-a319-23db45ff8984">

---

investments 5.5.0

**Comment by KonishchevDmitry** [comment]
Supported in v5.5.1.
