### ISSUE TITLE
Upcoming `qtrac-retest` crate deletion

### ISSUE THREAD

**Issue by Turbo87** [KonishchevDmitry/investments#84]
The author of https://crates.io/crates/qtrac-retest has contacted the crates.io team and requested to have all of their projects deleted from crates.io. Since the crates of this author have a couple of reverse dependencies we thought it might be good to notify them of the upcoming removal. We haven't set a removal date yet, but in the next couple of weeks the `qtrac-retest` crate will disappear from crates.io. If you want to continue using it you could potentially fork and republish it.

**Comment by KonishchevDmitry** [comment]
Thanks a lot for the notification!
